services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      # - "6334:6334"  para grpc
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend_net

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    volumes:
      - redis_data_dev:/var/lib/redis/data
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file: .env
    networks:
      - backend_net

  celery:
    build: ./app
    command: >
      sh -c "
      mkdir -p /backend/prometheus &&
      celery -A app.core.celery_app worker --loglevel=info
      "
    depends_on:
      - redis
    env_file: .env
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/backend/prometheus
    volumes:
      - .:/backend
      - shared_data:/backend/api_data
    networks:
      - backend_net

  api:
    build: ./app
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/backend/prometheus
    volumes:
      - hf_cache:/root/.cache
      - .:/backend
      - shared_data:/backend/api_data
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "
      rm -rf /backend/prometheus/* &&
      mkdir -p /backend/prometheus &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - qdrant
    networks:
      - backend_net

  ollama:
    profiles:
      - ollama
    image: ollama/ollama:rocm
    devices:
      - "/dev/dri:/dev/dri"
    ports:
      - 11434:11434
    volumes:
      - .:/backend
      - ./ollama/ollama:/root/.ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
    networks:
      - backend_net

  prometheus:
    profiles:
      - monitoring
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend_net

  grafana:
    profiles:
      - monitoring
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend_net

volumes:
  qdrant_data:
  hf_cache:
  redis_data_dev:
  shared_data:
  grafana-storage:

networks:
  backend_net:
    driver: bridge
