services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      # - "6334:6334"  para grpc
    volumes:
      - qdrant_data:/qdrant/storage
    mem_limit: 512m
    mem_reservation: 256m

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data_dev:/var/lib/redis/data
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file: .env

  celery:
    build: ./app
    command: celery -A app.core.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file: .env
    volumes:
      - .:/backend
      - shared_data:/backend/api_data

  api:
    build: ./app
    volumes:
      - hf_cache:/root/.cache
      - .:/backend
      - shared_data:/backend/api_data
    env_file:
      - .env
    ports:
      - "8000:8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    mem_limit: 768m
    mem_reservation: 384m
    depends_on:
      - qdrant
    environment:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
      MKL_NUM_THREADS: 1
      NUMEXPR_NUM_THREADS: 1
      TORCH_NUM_THREADS: 1

volumes:
  qdrant_data:
  hf_cache:
  redis_data_dev:
  shared_data:
